<h1>Setup</h1>

<form action="/setup" method="post">
	<input type="hidden" name="step" value="1" />
	<fieldset>
		<legend>Login Credentials</legend>

		<p>
			<label>Username</label>
			<input type="text" name="username" />
		</p>

		<p>
			<label>Password</label>
			<input type="password" name="password1" />
		</p>

		<p>
			<label>Confirm Password</label>
			<input type="password" name="password2" />
		</p>

		<p class="submit">
			<input type="submit" value="Continue" />
		</p>
	</fieldset>
</form>